insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/1", "Random Stepper", 1, 1);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/2", "Wagnerian", 1, 2);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/3", "PickdSynGtr", 1, 3);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/4", "Single", 1, 4);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/5", "Accenture FB", 1, 5);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/6", "Progenesis", 1, 6);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/7", "SingingFilter", 1, 7);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/8", "Assign1 to BD FB", 1, 8);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/9", "Tom Sawyer", 1, 9);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/10", "Santiago", 1, 10);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/11", "FeedbackSync", 1, 11);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/12", "Triangular", 1, 12);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/13", "RapidArpFB", 1, 13);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/14", "MOONSTER", 1, 14);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/15", "Rokoko", 1, 15);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/16", "Aliens", 1, 16);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/17", "Sync-otic", 1, 17);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/18", "Evolver", 1, 18);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/19", "Noiz Machine FB", 1, 19);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/20", "Base (Hold) FB", 1, 20);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/21", "PlayLOnLETitGO", 1, 21);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/22", "Epic Brass", 1, 22);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/23", "Soft Triangles", 1, 23);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/24", "Plod", 1, 24);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/25", "G-Rap Theme", 1, 25);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/26", "Taurus", 1, 26);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/27", "3OH3", 1, 27);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/28", "Acid Rez", 1, 28);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/29", "Whippersnap", 1, 29);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/30", "P5 3-2 Sync", 1, 30);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/31", "Fortunate Guy", 1, 31);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/32", "Bandpassed", 1, 32);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/33", "bOOmChik", 1, 33);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/34", "Jazzophonetic", 1, 34);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/35", "Crystal", 1, 35);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/36", "Evokativ", 1, 36);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/37", "Helicopters", 1, 37);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/38", "CheeseIntro", 1, 38);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/39", "Kik Bass", 1, 39);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/40", "Ski Canyon Delay", 1, 40);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/41", "Stop It", 1, 41);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/42", "Tonga Conga", 1, 42);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/43", "Talker", 1, 43);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/44", "Sync Floyd Dark", 1, 44);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/45", "Wow Saws", 1, 45);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/46", "Opening Up", 1, 46);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/47", "Chaos", 1, 47);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/48", "Classic Square", 1, 48);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/49", "HiwayPatrolBass", 1, 49);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/50", "Haus Organ", 1, 50);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/51", "Rezzy Neeyowng", 1, 51);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/52", "Tricky Sweeper", 1, 52);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/53", "Deep eMotion", 1, 53);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/54", "Condor", 1, 54);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/55", "Bridge Seq", 1, 55);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/56", "Deep", 1, 56);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/57", "AttackFilterBass", 1, 57);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/58", "Synth Cello", 1, 58);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/59", "Rubber Bandz", 1, 59);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/60", "Sample+Hold It", 1, 60);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/61", "Clean Glass Bell", 1, 61);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/62", "Elastik", 1, 62);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/63", "Itty Bit", 1, 63);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/64", "BangForTheBuckFB", 1, 64);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/65", "Bass Pedals", 1, 65);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/66", "Hellabass", 1, 66);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/67", "P'08 inb da House", 1, 67);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/68", "N.U.N.I.", 1, 68);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/69", "Rubycorn Dream", 1, 69);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/70", "PW Downsweep", 1, 70);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/71", "Saw Upsweep", 1, 71);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/72", "Swirl", 1, 72);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/73", "Offspring FB", 1, 73);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/74", "Kalimbatron", 1, 74);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/75", "Moroder 1", 1, 75);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/76", "PanAnalog", 1, 76);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/77", "Lo Contra", 1, 77);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/78", "Harmonika", 1, 78);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/79", "Solo French Horn", 1, 79);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/80", "Royal Synth Horn", 1, 80);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/81", "Small Pipes", 1, 81);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/82", "DetunedSawLead", 1, 82);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/83", "SizzleSawLead", 1, 83);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/84", "Juice Squeezer", 1, 84);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/85", "Tape Saturation", 1, 85);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/86", "Half Live", 1, 86);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/87", "Ice Planet", 1, 87);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/88", "Mosquito", 1, 88);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/89", "Box o'Morons", 1, 89);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/90", "No Corn Yet", 1, 90);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/91", "Geisha", 1, 91);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/92", "Bowng Bass", 1, 92);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/93", "Pressure Squared", 1, 93);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/94", "Tarkus (F1 seq)", 1, 94);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/95", "SlowWahFastClav", 1, 95);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/96", "TriPulseAtkLd", 1, 96);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/97", "BraggoBeat", 1, 97);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/98", "Craftsman", 1, 98);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/99", "Basement FB", 1, 99);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/100", "Rasp Bass Line", 1, 100);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/101", "Waver", 1, 101);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/102", "Phasing Bass", 1, 102);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/103", "Abrasive", 1, 103);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/104", "Oscs+HFOs FB", 1, 104);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/105", "T8 String", 1, 105);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/106", "String Phaze", 1, 106);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/107", "MonoOddy", 1, 107);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/108", "Fusion Bass", 1, 108);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/109", "Fiiilters", 1, 109);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/110", "2 Much Red Bull", 1, 110);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/111", "Sync Glider", 1, 111);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/112", "Kalliope", 1, 112);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/113", "Ultravox", 1, 113);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/114", "Wet Bass", 1, 114);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/115", "Hood Beat", 1, 115);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/116", "Mr. Fusion", 1, 116);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/117", "Harp Arp", 1, 117);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/118", "Frnknstein(Hold)", 1, 118);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/119", "Come Together", 1, 119);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/120", "Take Off", 1, 120);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/121", "VariClap", 1, 121);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/122", "Blip", 1, 122);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/123", "Zap", 1, 123);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/124", "Drop Da Bomb", 1, 124);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/125", "Wind", 1, 125);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/126", "Thunder FB", 1, 126);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/127", "Seashore FB", 1, 127);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "1/128", "Introverted", 1, 128);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/1", "D-mode", 2, 1);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/2", "Sync Sweep", 2, 2);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/3", "Curtis Filterz", 2, 3);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/4", "Trancesexual", 2, 4);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/5", "InvertdFiltrSaws", 2, 5);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/6", "RubbrPickBassFB", 2, 6);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/7", "noOB Brass 2pole", 2, 7);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/8", "Descending", 2, 8);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/9", "Steps", 2, 9);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/10", "Steel Can Band", 2, 10);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/11", "FakeDelay", 2, 11);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/12", "The Big Diss", 2, 12);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/13", "RubbrpunchBasFB", 2, 13);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/14", "Mini", 2, 14);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/15", "Clavanomic", 2, 15);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/16", "Brassy", 2, 16);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/17", "WelcomeBackELP", 2, 17);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/18", "BouncingDotz", 2, 18);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/19", "Tuned Trash Lids", 2, 19);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/20", "Goovular", 2, 20);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/21", "Octave Diver MW", 2, 21);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/22", "PhattSubFB", 2, 22);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/23", "WetSawtooth", 2, 23);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/24", "Red Fizzz", 2, 24);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/25", "Gamma", 2, 25);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/26", "TonewheelOrgan", 2, 26);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/27", "MassiveFakePWM", 2, 27);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/28", "Ober SQUARE", 2, 28);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/29", "Ambush", 2, 29);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/30", "Zen Master", 2, 30);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/31", "Pinball", 2, 31);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/32", "Fired Bassist", 2, 32);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/33", "Direful", 2, 33);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/34", "Universe", 2, 34);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/35", "Homeless", 2, 35);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/36", "Rezodrone", 2, 36);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/37", "Petsche", 2, 37);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/38", "BladeRunner", 2, 38);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/39", "Lost In Thought", 2, 39);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/40", "Squelch", 2, 40);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/41", "Punchy Kick", 2, 41);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/42", "MellowBassFB", 2, 42);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/43", "ManInTheMoon", 2, 43);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/44", "80iesSynthPop", 2, 44);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/45", "VeloXpand", 2, 45);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/46", "Pig Pen", 2, 46);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/47", "Carillon", 2, 47);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/48", "Flutish", 2, 48);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/49", "Solo Reed", 2, 49);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/50", "Horn Swell", 2, 50);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/51", "Jazz Bass Trip", 2, 51);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/52", "DirtDevilRaveFB", 2, 52);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/53", "Tube Fire", 2, 53);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/54", "LowKey", 2, 54);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/55", "Zardoz", 2, 55);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/56", "Sync Floyd", 2, 56);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/57", "Nebula", 2, 57);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/58", "MadMusicBox", 2, 58);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/59", "BottleClink", 2, 59);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/60", "Tennis Beat", 2, 60);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/61", "Ana Kick 1", 2, 61);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/62", "Acid Saw", 2, 62);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/63", "Acid Square", 2, 63);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/64", "Acid Pulse", 2, 64);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/65", "Podpogo pop", 2, 65);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/66", "Ana Kick 2", 2, 66);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/67", "MetalNoizLoopFB", 2, 67);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/68", "AnalogCruizer", 2, 68);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/69", "Mode 1", 2, 69);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/70", "KJPW", 2, 70);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/71", "Spartacus", 2, 71);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/72", "Switched On", 2, 72);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/73", "Steady", 2, 73);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/74", "Different", 2, 74);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/75", "Compressed", 2, 75);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/76", "Git da funk out", 2, 76);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/77", "Dual Seq", 2, 77);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/78", "Japan", 2, 78);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/79", "Bugger", 2, 79);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/80", "Pure Prophet", 2, 80);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/81", "Sonof ProOne", 2, 81);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/82", "Oh Bee", 2, 82);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/83", "Mud Acid", 2, 83);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/84", "Zenhog", 2, 84);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/85", "Bone-imba", 2, 85);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/86", "Subtractive", 2, 86);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/87", "Combo Organ", 2, 87);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/88", "Roadzy Bass", 2, 88);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/89", "Tangram", 2, 89);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/90", "Wo-Wa-Wa", 2, 90);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/91", "Rubber Rez FB", 2, 91);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/92", "Virtuously", 2, 92);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/93", "P '08 Pulse", 2, 93);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/94", "Octave Glider", 2, 94);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/95", "E3Rep", 2, 95);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/96", "Omni Bass", 2, 96);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/97", "Filter Chant", 2, 97);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/98", "Whassup ?", 2, 98);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/99", "Organ-ik", 2, 99);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/100", "Pulse Shifter", 2, 100);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/101", "Scrape Dry Rust", 2, 101);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/102", "Detuned Poles", 2, 102);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/103", "Brainwaves", 2, 103);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/104", "Forbidden Planet", 2, 104);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/105", "Dr. Dray", 2, 105);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/106", "Soft Dark Bite", 2, 106);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/107", "Catweazle", 2, 107);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/108", "Cowbell Dance", 2, 108);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/109", "Syncussion", 2, 109);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/110", "Dial Tonez", 2, 110);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/111", "Blubber 2", 2, 111);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/112", "Pipe-ish", 2, 112);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/113", "Stacker", 2, 113);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/114", "Moddisee", 2, 114);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/115", "ReversePlayback", 2, 115);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/116", "Classic Synth", 2, 116);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/117", "Softie", 2, 117);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/118", "Aluminum", 2, 118);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/119", "Heavy Weather", 2, 119);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/120", "Rainstorm", 2, 120);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/121", "HighVoltage", 2, 121);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/122", "Transformer", 2, 122);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/123", "R2D2", 2, 123);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/124", "Morse Codec", 2, 124);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/125", "Come In", 2, 125);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/126", "Windchime", 2, 126);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "2/127", "Tron Cycle", 2, 127);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/128", "2600 Twitter", 3, 128);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/1", "Krakker", 3, 1);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/2", "Lemon Twist", 3, 2);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/3", "Fake Arp", 3, 3);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/4", "Tekk-notion", 3, 4);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/5", "D.C.    FB", 3, 5);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/6", "Solid Bottom FB", 3, 6);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/7", "ElectronnFB", 3, 7);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/8", "Coil Core  FB", 3, 8);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/9", "Video Beatz", 3, 9);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/10", "Fatso", 3, 10);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/11", "Bustle", 3, 11);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/12", "Alternative", 3, 12);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/13", "CrawlInMySkinFB", 3, 13);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/14", "Steam-Powered", 3, 14);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/15", "LoFi Rhythm", 3, 15);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/16", "Apprentice", 3, 16);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/17", "Plutonium Mine", 3, 17);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/18", "Marathon", 3, 18);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/19", "Bassic", 3, 19);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/20", "Latent Bass FB", 3, 20);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/21", "Rezidiv  FB", 3, 21);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/22", "Old School", 3, 22);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/23", "InsectLead FB", 3, 23);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/24", "BoingBoingFB", 3, 24);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/25", "Simplesizer FB", 3, 25);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/26", "Scratcher", 3, 26);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/27", "Hands-On", 3, 27);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/28", "PeeWeeEmm", 3, 28);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/29", "2-pole-brassy", 3, 29);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/30", "GlassRub", 3, 30);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/31", "FlexiBell", 3, 31);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/32", "ResoPWM  FB", 3, 32);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/33", "VeloSyncer", 3, 33);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/34", "AttakSub", 3, 34);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/35", "Rezotator", 3, 35);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/36", "ClickyWheels", 3, 36);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/37", "3-storied", 3, 37);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/38", "Chip Lead", 3, 38);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/39", "Loaded Full FB", 3, 39);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/40", "PressureBass FB", 3, 40);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/41", "Groundloop  FB", 3, 41);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/42", "Space House", 3, 42);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/43", "CannedRhythm", 3, 43);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/44", "Hold&Sample", 3, 44);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/45", "Staccato", 3, 45);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/46", "RetroMoPho", 3, 46);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/47", "CurtiSquare", 3, 47);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/48", "DustyCircuitBell", 3, 48);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/49", "Raspy", 3, 49);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/50", "Shattering FB", 3, 50);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/51", "Popa Joey", 3, 51);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/52", "Space Pong FB", 3, 52);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/53", "Chillmatrix", 3, 53);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/54", "Generator", 3, 54);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/55", "Cold Turkey FB", 3, 55);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/56", "Brat", 3, 56);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/57", "Ignition", 3, 57);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/58", "Spit 'n Spank", 3, 58);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/59", "Machine", 3, 59);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/60", "Overclock", 3, 60);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/61", "SteppyDrone FB", 3, 61);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/62", "Mini Amp", 3, 62);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/63", "InverseTriadFB", 3, 63);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/64", "The Real Thing", 3, 64);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/65", "Axis", 3, 65);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/66", "PercuLoop  FB", 3, 66);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/67", "Suspicious", 3, 67);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/68", "Weirdomat", 3, 68);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/69", "Juggernaut FB", 3, 69);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/70", "MightyTouchy", 3, 70);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/71", "Tertianus", 3, 71);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/72", "Thereminna", 3, 72);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/73", "Ion Trails", 3, 73);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/74", "MoPhat", 3, 74);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/75", "Mo Tuba", 3, 75);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/76", "Snapper  FB", 3, 76);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/77", "Perpendicular", 3, 77);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/78", "Hyde Park", 3, 78);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/79", "Remastered", 3, 79);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/80", "TapeVox", 3, 80);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/81", "InputGain FB", 3, 81);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/82", "Glockenz", 3, 82);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/83", "Playerz 5th", 3, 83);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/84", "GameboyLead", 3, 84);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/85", "Still Nice", 3, 85);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/86", "Thoroughlead", 3, 86);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/87", "Unpredictable FM", 3, 87);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/88", "Tormentor", 3, 88);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/89", "Breed", 3, 89);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/90", "Rubens-Bass FB", 3, 90);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/91", "Rap-It", 3, 91);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/92", "Pesky Lead", 3, 92);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/93", "Lamento", 3, 93);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/94", "AM-Bass", 3, 94);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/95", "Sparkplug", 3, 95);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/96", "Modded Farfisa", 3, 96);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/97", "PanoBass", 3, 97);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/98", "Camembert  FB", 3, 98);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/99", "AccuBass  FB", 3, 99);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/100", "YellowTool  FB", 3, 100);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/101", "SubOscils", 3, 101);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/102", "Hornet's Nest", 3, 102);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/103", "Touch Me", 3, 103);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/104", "Gravelly", 3, 104);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/105", "Peavish", 3, 105);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/106", "HighRes", 3, 106);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/107", "Catwalk", 3, 107);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/108", "Catwalk", 3, 108);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/109", "MultiKick", 3, 109);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/110", "Alimbic", 3, 110);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/111", "Jupiter Storm", 3, 111);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/112", "Arc-Welding", 3, 112);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/113", "Neutrinos", 3, 113);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/114", "Chopper FB", 3, 114);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/115", "Ear-Piercing", 3, 115);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/116", "Bosons", 3, 116);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/117", "Cauldron   FB", 3, 117);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/118", "Pressure Valve", 3, 118);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/119", "NoiseGainFB", 3, 119);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/120", "Power Supply", 3, 120);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/121", "Geiger Counter", 3, 121);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/122", "Sleepin Droid", 3, 122);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/123", "Ellipse", 3, 123);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/124", "Richochet", 3, 124);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/125", "E=Mc2", 3, 125);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/126", "VeloPercussion", 3, 126);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/127", "Filter Test", 3, 127);  
insert into patches (src_model, src_id, src_name, midi_lsb, midi_pgm) values ("Mopho", "3/128", "New Test", 3, 128);  