insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A01","Stab Saw","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A02","Synth Lana","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A03","Evolution","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A04","Boost Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A05","Dirty Sync","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A06","Zoop Mania","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A07","Ice Field","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A08","Lounge Organ","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A09","MG Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A10","GatesOfHell","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A11","PWM Strings","Strings");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A12","Turn Wheel","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A13","Synth Tp","Synth Brass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A14","DWGS WaveSeq","Wave Seq");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A15","Drive Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "A16","Surrounded","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B01","Lazy Pitch","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B02","Stairs Pad","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B03","Silk Pad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B04","Zap Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B05","Uni Synth","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B06","PsycheTrance","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B07","Deep Bell","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B08","Synth Clav","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B09","Line Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B10","SearchEngine","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B11","Voice /A/","Choir");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B12","Far Horizon","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B13","Glass","Synth Soft");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B14","Random","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B15","Jami Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "B16","Loomy","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C01","Poly Line","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C02","Krazy Arpy 1","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C03","Mod3&4 Squad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C04","What D' Time","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C05","Healing","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C06","Auto Disco","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C07","Candy Box","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C08","Vintage EP","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C09","Mini Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C10","Tap Lead","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C11","Royal Pad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C12","Freq Lead","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C13","Solemn Brass","Synth Brass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C14","IZDISA-WS","Wave Seq");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C15","House Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "C16","Invaders","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D01","Ana Fuzz","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D02","Water Edge","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D03","Reactor Pad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D04","MS-101 Sqr","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D05","Edge Lead","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D06","Goa Trax","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D07","Retro BD/SD","Synth Drum");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D08","Wet Reed","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D09","Fat Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D10","Flashlight","Synth Motion");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D11","Stream Pad","Strings");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D12","EP Fusion Ld","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D13","TremoloSynth","Synth Soft");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D14","Motion Pad","Synth Motion");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D15","Banana Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "D16","Bad Dream","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E01","Century Stab","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E02","Simple Arpg","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E03","Tin Memoreez","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E04","Organ Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E05","High Voltage","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E06","Trip Planet","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E07","Dry Plant","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E08","Reed Piano","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E09","Magnum Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E10","Mad Lead","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E11","Belly","Choir");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E12","BackInTheDay","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E13","Synth Brass","Synth Brass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E14","ElectroShock","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E15","Bakin' Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "E16","Telephone","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F01","Golden Synth","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F02","Blue&White","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F03","Pan Tran","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F04","Warp Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F05","Killa Lead","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F06","Tribe'n Beat","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F07","Bound Ball","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F08","CuttingArpg","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F09","Bass Machine","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F10","Trip 2 Ibiza","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F11","Ana Strings","Strings");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F12","Past Mind","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F13","Future Vibe","Synth Soft");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F14","Euro Synthe","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F15","Digy Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "F16","Thunder","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G01","Square Comp","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G02","Krazy Arpy 2","Arpeggio");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G03","Sweep Pad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G04","Sub Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G05","Phenomenon","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G06","Ready 2 Air","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G07","X-Mod Perc","Bell");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G08","BritishOrgan","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G09","80's Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G10","Min.Deal","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G11","Astral Vox","Choir");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G12","Rez Lead","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G13","Soft Brass","Synth Brass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G14","CPU Talk","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G15","Phunk Bass","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "G16","Jet Set 2000","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H01","Poly400","Synth Hard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H02","Diginator","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H03","Light Pad","Synth Pad");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H04","Bass&5thLead","Synth Bass");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H05","Woody's Lead","Synth Lead");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H06","Filter Muzik","Sequence");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H07","TimeZone SFX","S.E.");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H08","Pulse Comp","Keyboard");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H09","Vocoder Ens","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H10","Vocoder Cho","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H11","Vocoder Wah","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H12","V ocoderPulse","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H13","VoiceChanger","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H14","Vocodevil","Vocoder");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H15","AudioIn INIT","AudioIn");
insert into patches (src_model, src_id, src_name, src_category) values ("MS2K", "H16","Init Program","Init Program");
