insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A000", "Portamento Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A001", "StereoPiano mf/f", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A002", "Centerfuge", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A003", "Session Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A004", "Mashed Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A005", "HardPulse Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A006", "Session Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A007", "Jazz Organ 1", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A008", "Vibraphone 2", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A009", "Saw Strings", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A010", "Saw OD Bass/Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A011", "SiniSTAR Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A012", "Nylon Guitar 2", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A013", "Ping/Pong Synth", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A014", "Harmonica-Wah", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A015", "THEY were here", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A016", "Fast Saw Synth", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A017", "EP Bright mf/f", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A018", "PunchBowl HIT", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A019", "Tape Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A020", "Standard Kit 3", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A021", "Velo Scat Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A022", "Trumpet Duo", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A023", "BX3 Velo Switch", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A024", "Analog Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A025", "Overture Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A026", "2VCO Planet Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A027", "Club Ac Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A028", "Mono Guitar Lead", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A029", "SpikeyUnisyn", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A030", "Flute Vibrato", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A031", "Cymbalis", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A032", "Ghostly Popper", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A033", "Tremolo Wurly", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A034", "Saw Arpeggiator", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A035", "StringsQuartet 2", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A036", "DWGS Sync2 Knob1", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A037", "Nice&Expensive", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A038", "5th Stab", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A039", "Distortion Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A040", "Monkey Skulls", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A041", "Korgmatose", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A042", "Dance Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A043", "SuperSwitch Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A044", "A.Guitar Gliss.", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A045", "Time Stood Still", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A046", "Sax Ensemble", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A047", "Orbiting Probes", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A048", ">Fast Reaction<", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A049", "Funky Clav", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A050", "NetherlandHit", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A051", "D'n'B/GarageBass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A052", "Psycho Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A053", "Aah Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A054", "Horns & Ensemble", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A055", "Transweep", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A056", "Chorus E.Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A057", "FlutaSonic Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A058", "Ripper", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A059", "Low Finger Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A060", "Power-Chords&FX", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A061", "Motion Saw", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A062", "Oboe Vibrato", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A063", "Xpanded Voice", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A064", "Polysix Pad", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A065", "M1 Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A066", "Chord Trigger", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A067", "Hybrid Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A068", "Mega Drum Hit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A069", "M1 Organ Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A070", "Velo Resonant", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A071", "Additive Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A072", "Digital Bells 1", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A073", "ClassicAnaPad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A074", "DetunedSuperLead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A075", "Bass-Depot", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A076", "Processed E.Gtr.", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A077", "LightOfTheSource", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A078", "Classic Tines", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A079", "Big Break Down", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A080", "Paddy Whack", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A081", "Analog E.Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A082", "Chipper Dayglow", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A083", "Acid Square Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A084", "Filter Drums", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A085", "Digital Voice", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A086", "Trumpets&Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A087", "Velo Pulse Clav", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A088", "Ensemble Bell", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A089", "ASineOfTheTimes", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A090", "JuicyBleep-age", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A091", "DarkCore Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A092", "Harp", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A093", "Swirling Dreams", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A094", "Fisa Americana", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A095", "Monster Island", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A096", "Reso Comp", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A097", "DarkTineStage EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A098", "Progressv Trance", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A099", "PizzAnsamble", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A100", "! {Tricky} Kit !", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A101", "Deep Detune Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A102", "Cosmic Furnace", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A103", "Pipe Mixture", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A104", "Krystal Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A105", "Strings Synth", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A106", "Detox Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A107", "Wah Space Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A108", "Da Mute...Joy -Y", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A109", "Sinistar*Android", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A110", "Piano Pad", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A111", "JoyStick Machine", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A112", "Super Saw Brass", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A113", "Romance Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A114", "Techno Organ Hit", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A115", "Boost RnB Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A116", "BD&SD Kit 1", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A117", "Talkin' Keys", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A118", "Trombone Ens.", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A119", "PowerRezSweep", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A120", "Thin Bell-s-park", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A121", "Cross Sweeper", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A122", "Nu HPF Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A123", "Motion Bass/Lead", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A124", "Jazz Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A125", "Space Pod for 2", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A126", "TenorSax Growl-Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "A127", "Steam Sweeps", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B000", "Big Sweep Stab", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B001", "Acoustic Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B002", "Flip Blip", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B003", "Arco Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B004", "Trance/GarageKit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B005", "Bass 4 Da Phunk", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B006", "Burnin' Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B007", "Full Drawbars", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B008", "Bali Gamelon", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B009", "Breakdown String", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B010", "Phat Saw Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B011", "Drive Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B012", "AcousticGuitar 1", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B013", "VCF Modulation", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B014", "Harmonica", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B015", "Soundscapes", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B016", "Rezbo", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B017", "Stereo E.Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B018", "BlastFromDaPast", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B019", "Vintage Stringz", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B020", "Standard Kit 1", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B021", "Dah Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B022", "Trombone Hard", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B023", "Classic Click", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B024", "VS Bell Boy", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B025", "Reactor Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B026", "MonoSynGtr LEAD", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B027", "Acoustic Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B028", "Wet Dist. Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B029", "Crimson 5ths", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B030", "Old Shakuhachi", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B031", "Loop-Iteria", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B032", "Perky Bleeper", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B033", "Velo Whirly", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B034", "Auto Pilot", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B035", "Small StringsEns", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B036", "WellAardHouse", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B037", "Slow Choir ST", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B038", "Garage PWM", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B039", "Perc Short Decay", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B040", "Log Drum", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B041", "Rez. Down", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B042", "Espress Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B043", "Slap Bass v/s", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B044", "Sitar Sitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B045", "Tinklin' Pad", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B046", "SopranoSax Br.-Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B047", "The Great Wall", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B048", "Mega Big Synth", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B049", "Clav", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B050", "Percussive Hits", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B051", "Drum'n'Bass Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B052", "Psycho Pitch Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B053", "Woh Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B054", "Classic Fanfare", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B055", "Blasta Brasster", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B056", "Strato-Chime", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B057", "Clouds of Air", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B058", "Nu Skool Bleeps", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B059", "Stein Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B060", "Joystick Gtr(-Y)", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B061", "Transformation", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B062", "DoubleReed", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B063", "<Techno Vox Box>", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B064", "InverseSQwave", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B065", "Warm E.Grand", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B066", "VCF Sample&Hold", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B067", "AnalogStrings1&2", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B068", "Dragon Gong", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B069", "Tekno Organ*Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B070", "5th Sweeper", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B071", "Dark Jazz-Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B072", "Hybrid Bell", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B073", "Digi Ice Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B074", "Detune Leader", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B075", "House Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B076", "SingleCoil+Piezo", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B077", "BPF Sweep Pad", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B078", "Night Tines EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B079", "Sonic Blast", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B080", "Future Syn Pad", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B081", "SynPiano X", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B082", "Jungle Melody", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B083", "Ana Bass 1", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B084", "Drum'n'Bass Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B085", "Fresh Breath", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B086", "Fat Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B087", "Turn Back Stab", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B088", "Tropico Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B089", "Simple Sine Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B090", "Seq DDL Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B091", "2 Step Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B092", "Koto", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B093", "Astral Dreams", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B094", "Musette", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B095", "Dark Night", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B096", "Metalic Rez", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B097", "Dyno Tine EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B098", "Goa Message", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B099", "PizzicatoSection", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B100", "Orchestra&Ethnic", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B101", "The Tea-Bea", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B102", "Synth Sweeper", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B103", "Church Pipes", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B104", "Tinkle Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B105", "Noble Brite Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B106", "Old & Analog", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B107", "Nu Skool Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B108", "Funkin' Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B109", "Spectrum Alloy", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B110", "HarpsyKorg 8'+4'", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B111", "VenusianStories", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B112", "SynthBrass", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B113", "Phantom Of Tine", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B114", "Rave Synth", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B115", "Dark R&B Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B116", "BD&SD Kit 2", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B117", "Take Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B118", "Glen & The Boys", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B119", "Dual Filterz", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B120", "Future Bell", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B121", "Ultra Res. Sweep", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B122", "Glide Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B123", "Nasty Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B124", "Vintage Stratt", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B125", "Symphonic Waves", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B126", "AltoSax2Breath-Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "B127", "DJ Touch", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C000", "EuphoricTrancer", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C001", "Attack Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C002", "Scattersynth", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C003", "StSlowStringsEXP", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C004", "HipHop Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C005", "Ana Bass 2", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C006", "SFZ Brass ST", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C007", "Gospel PercOrgan", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C008", "Marimba", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C009", "Symphonic Ensemb", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C010", "BrightPulseLead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C011", "DistortedTeaBea", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C012", "Nylon Guitar 1", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C013", "Gating Voice Pad", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C014", "Spitz Bottle", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C015", "MotionSoundTrack", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C016", "Rez. Sweep", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C017", "EP Dark mf/f", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C018", "StaccatoPizzHit", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C019", "WatcherOfTheSky", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C020", "Standard Kit 2", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C021", "Choir of Light", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C022", "Trumpet", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C023", "Percussion BX3", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C024", "Moving Bellz", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C025", "Tsunami Waves", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C026", "HipHop Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C027", "Fretless Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C028", "Mute Monster", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C029", "Aqua Phonics", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C030", "Jazz Clarinet", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C031", "Goa Lover", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C032", "Analog Piano", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C033", "Classic Wurly", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C034", "Noise Shot", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C035", "StringsQuartet 1", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C036", "X-Mod Raver", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C037", "Garage SQ Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C038", "Power Snap Synth", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C039", "Old Tone-Wheel", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C040", "Velo Kalimba", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C041", "Antartic Wind", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C042", "Smooth Sine Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C043", "E.Bass Pick 2", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C044", "A.Guitar NatATK", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C045", "Pods In The Pad", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C046", "Reed Of Power", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C047", "New Voyage", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C048", "Noisy Stabber", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C049", "Sticky Rez Clav", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C050", "Organ Impact", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C051", "UK Garage Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C052", "UGLY HoUSe Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C053", "Oooh Voices ST", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C054", "Film Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C055", "Polyphonic Line", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C056", "Dynamic E.Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C057", "Ravelian Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C058", "Fat Syn Sync", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C059", "E.Bass Finger", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C060", "Feedback D. Gtr.", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C061", "Cyclic X-Fades", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C062", "English Horn", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C063", "Gliding Squares", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C064", "Square Snaps", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C065", "90's Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C066", "Synchro Science", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C067", "HybridStrg/Choir", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C068", "Marc Tree", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C069", "Hard Velo Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C070", "Cyber Choir", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C071", "Sine DWGS-Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C072", "Digital Bells 2", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C073", "Harmonic Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C074", "Digitized Raver", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C075", "Feedback MG Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C076", "PedalSteelGuitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C077", "OXYGEN", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C078", "Hybrid Digi EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C079", "Video Blaster", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C080", "Pop Synth Pad", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C081", "White Pad EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C082", "Big Hit in India", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C083", "Jungle Rez Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C084", "D'n'B Gate Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C085", "The AirVox", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C086", "Tight Brass", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C087", "Thunderlog", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C088", "Bottle-Bell", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C089", "Smoothy Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C090", "Syncro City", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C091", "Ramp Jungle Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C092", "Old 12-String", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C093", "Flying Machines", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C094", "Fisa Cassotto", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C095", "Compu-shift", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C096", "S&H Reso Comp", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C097", "Pro-Dyno EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C098", "Motion Raver", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C099", "Octave Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C100", "Percussion Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C101", "Blaster Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C102", "Band Passed", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C103", "M1 Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C104", "GlassBell Bright", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C105", "Analog Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C106", "Octo Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C107", "Karma Sutra", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C108", "CleanMute-Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C109", "Stereo Rez Sweep", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C110", "Theatrical Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C111", "Distant Lights", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C112", "Soft Synth Brass", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C113", "Sweeping EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C114", "Techno Stat", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C115", "Phat Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C116", "Wild Wasp", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C117", "Vocalscaping", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C118", "Big Band Plunger", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C119", "Filter Morpher", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C120", "Breathy Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C121", "Cinema Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C122", "Electro Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C123", "30303 Mega Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C124", "E.G. Harmonics", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C125", "Moon Talker", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C126", "TenorSax Brth.-Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "C127", "Wispy Dry Wind", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D000", "Comp Trance Stab", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D001", "PianoMezzoDark", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D002", "Bounce Shot", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D003", "Legato Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D004", "House Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D005", "Bazooka Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D006", "Brass Of Power", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D007", "Jazz Organ 2", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D008", "Mondo'Rimba", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D009", "Money Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D010", "Square Wave Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D011", "The Growler", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D012", "FingertipsGuitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D013", "Flashlight Pad", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D014", "Recorder", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D015", "One Note Stories", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D016", "Square Rez", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D017", "Vintage EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D018", "Brass Impact Hit", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D019", "The Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D020", "Jazz/Brush Kits", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D021", "Ooh/Aah VoicesST", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D022", "Muted Trumpet", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D023", "Killer B", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D024", "Magical Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D025", "{(Meditate})", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D026", "Trancer Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D027", "Sweet Fretless", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D028", "Amp D. Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D029", "Rezzo Release", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D030", "BambuSilverFlute", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D031", "CyborgFactoryHit", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D032", "The ANAPIZZ", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D033", "R&B E.Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D034", "Arp Twins", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D035", "Camera Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D036", "Busy Sync", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D037", "30303 Square", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D038", "Trumpet Ens.", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D039", "Dirty B", "Organ");
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D040", "Log Drum & Bells", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D041", "Freedom Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D042", "Thin AnaLead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D043", "E.Bass Pick 1", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D044", "Indian Stars", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D045", "OutOfTheClouds", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D046", "BariSax Growl -Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D047", "Hemispheres", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D048", "Techno Phonic", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D049", "Clav Snap", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D050", "Old Record Hit", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D051", "Cyber Tom", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D052", "That Heaven Vibe", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D053", "Aaah Voices ST", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D054", "French Horn Sect", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D055", "Garage Organ", "Organ");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D056", "Nu Strat", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D057", "Brass Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D058", "Brian's Sync", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D059", "SynBassRes", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D060", "Vox Wah Chicks", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D061", "Stereo WaveSweep", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D062", "Bassoon", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D063", "Flute Pad", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D064", "Syn Pizz", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D065", "ST Piano mp/f", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D066", "Arp Angeles", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D067", "Analog Velvet", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D068", "Clock It Out", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D069", "MG Pulse Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D070", "Power Saw", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D071", "Formant Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D072", "Vibraphone 1", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D073", "StereoStringsEXP", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D074", "Syn Pipes", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D075", "Digi Syn Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D076", "PiezoMix Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D077", "Dolphin Ride", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D078", "Studio Stage EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D079", "Glass Vox", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D080", "Ana Brass/Lead", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D081", "Reson Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D082", "Hit Me 2 Times!!", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D083", "Euro 8va Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D084", "WAcKy HiPHop Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D085", "Vocalesque", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D086", "Brass Expression", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D087", "Fire Wave", "FastSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D088", "Mallet Clocker", "Bell/Mallet");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D089", "Stereo Piano mf", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D090", "Sync Kronicity", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D091", "Poinker Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D092", "AcousticGuitar 2", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D093", "Station Of Waves", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D094", "MixFisaMaster", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D095", "Frozen Glaciers", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D096", "AStabInTheDark", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D097", "Pro-Stage EP", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D098", "Wild Arp", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D099", "Stereo Strings", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D100", "Processed Kit", "Drums");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D101", "Acid Dist Bass", "Bass/Synth Bass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D102", "Few Bows Here", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D103", "Arctic Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D104", "Classic E.Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D105", "Mellow Movie Pad", "SlowSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D106", "AMSFeedbackLead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D107", "Classic F.Horn", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D108", "Indian Frets Gtr", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D109", "Virtual Traveler", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D110", "Flute", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D111", "Vanishing Planet", "SE");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D112", "Symphonic Bows", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D113", "Classic Piano", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D114", "Velo PowerStab", "Hit/Arpg");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D115", "Happy Vibe Lead", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D116", "Trumpet Section", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D117", "Dream Voices", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D118", "Octave Brass Exp", "Brass");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D119", "Solo Violin", "Strings");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D120", "Santur", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D121", "Full Vox Pad", "Vocal/Airy");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D122", "A leadload", "LeadSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D123", "L/R Piano(Knob1)", "Keyboard");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D124", "Spanish Guitar", "Guitar/Plucked");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D125", "Motion Ocean !", "MotionSynth");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D126", "AltoSax1 Growl-Y", "Woodwind/Reed");  
insert into patches (src_model, src_id, src_name, src_category) values ("TR61", "D127", "Init.Program", "Keyboard");  
